// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN1TdCi0ZkQgyofPTdKJu2Pijos1rzzDk',
    appId: '1:640869714625:web:3bf0769a146c8bf6ada240',
    messagingSenderId: '640869714625',
    projectId: 'tele-5d291',
    authDomain: 'tele-5d291.firebaseapp.com',
    storageBucket: 'tele-5d291.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYp5J1zQLx2dhSLtn5fW4BM674UDW1FiU',
    appId: '1:640869714625:android:8502fe9dc75c54b0ada240',
    messagingSenderId: '640869714625',
    projectId: 'tele-5d291',
    storageBucket: 'tele-5d291.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx0XMF3styCDPB9qb9BEBSM-IzisH7_4g',
    appId: '1:640869714625:ios:d2d78f28af70cf86ada240',
    messagingSenderId: '640869714625',
    projectId: 'tele-5d291',
    storageBucket: 'tele-5d291.firebasestorage.app',
    iosBundleId: 'com.example.teleStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx0XMF3styCDPB9qb9BEBSM-IzisH7_4g',
    appId: '1:640869714625:ios:d2d78f28af70cf86ada240',
    messagingSenderId: '640869714625',
    projectId: 'tele-5d291',
    storageBucket: 'tele-5d291.firebasestorage.app',
    iosBundleId: 'com.example.teleStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN1TdCi0ZkQgyofPTdKJu2Pijos1rzzDk',
    appId: '1:640869714625:web:a8a6e1e538dbd31dada240',
    messagingSenderId: '640869714625',
    projectId: 'tele-5d291',
    authDomain: 'tele-5d291.firebaseapp.com',
    storageBucket: 'tele-5d291.firebasestorage.app',
  );
}
